users: [
  "TALY"#,
  # "WEEH"
]

scenes:
  - track: "River2 - Bank Run"
    url: "https://www.velocidrone.com/leaderboard/23/117/1.11"
  - track: "River2 - Castle Shake Down"
    url: "https://www.velocidrone.com/leaderboard/23/118/1.11"
  - track: "River2 - HDR-CastleBlack-FIRE"
    url: "https://www.velocidrone.com/leaderboard/23/140/1.11"
  - track: "River2 - HDR-WhiteCastle-SP"
    url: "https://www.velocidrone.com/leaderboard/23/164/1.11"
  - track: "River2 - Pylons"
    url: "https://www.velocidrone.com/leaderboard/23/112/1.11"
  - track: "River2 - RiverSlalom"
    url: "https://www.velocidrone.com/leaderboard/23/119/1.11"
  - track: "River2 - SFPV Castle Run V2"
    url: "https://www.velocidrone.com/leaderboard/23/155/1.11"
  - track: "River2 - SFPV Dive"
    url: "https://www.velocidrone.com/leaderboard/23/156/1.11"
  - track: "River2 - SFPV Game of Drones"
    url: "https://www.velocidrone.com/leaderboard/23/132/1.11"
  - track: "River2 - SFPV H20Fire"
    url: "https://www.velocidrone.com/leaderboard/23/158/1.11"
  - track: "River2 - SFPV Lake House"
    url: "https://www.velocidrone.com/leaderboard/23/159/1.11"
  - track: "River2 - SFPV Matterhorn"
    url: "https://www.velocidrone.com/leaderboard/23/160/1.11"
  - track: "River2 - SFPV Torch Run V2"
    url: "https://www.velocidrone.com/leaderboard/23/162/1.11"

  - track: "SportsHall - Mini Rush"
    url: "https://www.velocidrone.com/leaderboard/21/72/1.11"
  - track: "SportsHall - MultiGP Round 2 FNL"
    url: "https://www.velocidrone.com/leaderboard/21/115/1.11"
  - track: "SportsHall - Pylons"
    url: "https://www.velocidrone.com/leaderboard/21/57/1.11"
  - track: "SportsHall - School Track"
    url: "https://www.velocidrone.com/leaderboard/21/58/1.11"


  - track: "Subway - Upstairs Downstairs"
    url: "https://www.velocidrone.com/leaderboard/15/36/1.11"
  - track: "Subway - All Stations"
    url: "https://www.velocidrone.com/leaderboard/15/39/1.11"
  - track: "Subway - Pylons"
    url: "https://www.velocidrone.com/leaderboard/15/33/1.11"
  - track: "Subway - RailRun"
    url: "https://www.velocidrone.com/leaderboard/15/167/1.11"
  - track: "Subway - Station Circuit"
    url: "https://www.velocidrone.com/leaderboard/15/35/1.11"
  - track: "Subway - Train Weave"
    url: "https://www.velocidrone.com/leaderboard/15/38/1.11"

  - track: "Hangar - Pylons"
    url: "https://www.velocidrone.com/leaderboard/3/20/1.11"
  - track: "Hangar - BoxCars"
    url: "https://www.velocidrone.com/leaderboard/3/7/1.11"
  - track: "Hangar - Porco Stadium"
    url: "https://www.velocidrone.com/leaderboard/3/49/1.11"

  - track: "Industrial Wasteland - Industrial Flag Race"
    url: "https://www.velocidrone.com/leaderboard/7/61/1.11"
  - track: "Industrial Wasteland - Porco Apocalypse"
    url: "https://www.velocidrone.com/leaderboard/7/63/1.11"
  - track: "Industrial Wasteland - Pylons"
    url: "https://www.velocidrone.com/leaderboard/7/21/1.11"
  - track: "Industrial Wasteland - SFPV Industry Loop"
    url: "https://www.velocidrone.com/leaderboard/7/85/1.11"
  - track: "Industrial Wasteland - SFPV Industry Power"
    url: "https://www.velocidrone.com/leaderboard/7/86/1.11"
  - track: "Industrial Wasteland - SFPV VRL 1"
    url: "https://www.velocidrone.com/leaderboard/7/121/1.11"
  - track: "Industrial Wasteland - Tower Drop"
    url: "https://www.velocidrone.com/leaderboard/7/31/1.11"