users: [
  "TALY"#,
  # "WEEH"
]

scenes:
#
# RIVER2
#
  - track: "River2 - Bank Run"
    url: "https://www.velocidrone.com/leaderboard/23/117/1.11"
  - track: "River2 - Castle Shake Down"
    url: "https://www.velocidrone.com/leaderboard/23/118/1.11"
  - track: "River2 - HDR-CastleBlack-FIRE"
    url: "https://www.velocidrone.com/leaderboard/23/140/1.11"
  - track: "River2 - HDR-WhiteCastle-SP"
    url: "https://www.velocidrone.com/leaderboard/23/164/1.11"
  - track: "River2 - Pylons"
    url: "https://www.velocidrone.com/leaderboard/23/112/1.11"
  - track: "River2 - RiverSlalom"
    url: "https://www.velocidrone.com/leaderboard/23/119/1.11"
  - track: "River2 - SFPV Castle Run V2"
    url: "https://www.velocidrone.com/leaderboard/23/155/1.11"
  - track: "River2 - SFPV Dive"
    url: "https://www.velocidrone.com/leaderboard/23/156/1.11"
  - track: "River2 - SFPV Game of Drones"
    url: "https://www.velocidrone.com/leaderboard/23/132/1.11"
  - track: "River2 - SFPV H20Fire"
    url: "https://www.velocidrone.com/leaderboard/23/158/1.11"
  - track: "River2 - SFPV Lake House"
    url: "https://www.velocidrone.com/leaderboard/23/159/1.11"
  - track: "River2 - SFPV Matterhorn"
    url: "https://www.velocidrone.com/leaderboard/23/160/1.11"
  - track: "River2 - SFPV Torch Run V2"
    url: "https://www.velocidrone.com/leaderboard/23/162/1.11"

#
# SPORTSHALL
#
  - track: "SportsHall - Mini Rush"
    url: "https://www.velocidrone.com/leaderboard/21/72/1.11"
  - track: "SportsHall - MultiGP Round 2 FNL"
    url: "https://www.velocidrone.com/leaderboard/21/115/1.11"
  - track: "SportsHall - Pylons"
    url: "https://www.velocidrone.com/leaderboard/21/57/1.11"
  - track: "SportsHall - School Track"
    url: "https://www.velocidrone.com/leaderboard/21/58/1.11"

#
# SUBWAY
#
  - track: "Subway - Upstairs Downstairs"
    url: "https://www.velocidrone.com/leaderboard/15/36/1.11"
  - track: "Subway - All Stations"
    url: "https://www.velocidrone.com/leaderboard/15/39/1.11"
  - track: "Subway - Pylons"
    url: "https://www.velocidrone.com/leaderboard/15/33/1.11"
  - track: "Subway - RailRun"
    url: "https://www.velocidrone.com/leaderboard/15/167/1.11"
  - track: "Subway - Station Circuit"
    url: "https://www.velocidrone.com/leaderboard/15/35/1.11"
  - track: "Subway - Train Weave"
    url: "https://www.velocidrone.com/leaderboard/15/38/1.11"

#
# HANGAR
#
  - track: "Hangar - Pylons"
    url: "https://www.velocidrone.com/leaderboard/3/20/1.11"
  - track: "Hangar - BoxCars"
    url: "https://www.velocidrone.com/leaderboard/3/7/1.11"
  - track: "Hangar - Porco Stadium"
    url: "https://www.velocidrone.com/leaderboard/3/49/1.11"

#
# INDUSTRIAL WASTELAND
#
  - track: "Industrial Wasteland - Industrial Flag Race"
    url: "https://www.velocidrone.com/leaderboard/7/61/1.11"
  - track: "Industrial Wasteland - Porco Apocalypse"
    url: "https://www.velocidrone.com/leaderboard/7/63/1.11"
  - track: "Industrial Wasteland - Pylons"
    url: "https://www.velocidrone.com/leaderboard/7/21/1.11"
  - track: "Industrial Wasteland - SFPV Industry Loop"
    url: "https://www.velocidrone.com/leaderboard/7/85/1.11"
  - track: "Industrial Wasteland - SFPV Industry Power"
    url: "https://www.velocidrone.com/leaderboard/7/86/1.11"
  - track: "Industrial Wasteland - SFPV VRL 1"
    url: "https://www.velocidrone.com/leaderboard/7/121/1.11"
  - track: "Industrial Wasteland - Tower Drop"
    url: "https://www.velocidrone.com/leaderboard/7/31/1.11"

#
# FOOTBALL STADIUM
#
  - track: "Football Stadium - Bexbach"
    url: "https://www.velocidrone.com/leaderboard/8/46/1.11"
  - track: "Football Stadium - Block Madness"
    url: "https://www.velocidrone.com/leaderboard/8/18/1.11"
  - track: "Football Stadium - Complex"
    url: "https://www.velocidrone.com/leaderboard/8/3/1.11"
  - track: "Football Stadium - CrossOver"
    url: "https://www.velocidrone.com/leaderboard/8/9/1.11"
  - track: "Football Stadium - FPV Dutchman Insanity"
    url: "https://www.velocidrone.com/leaderboard/8/80/1.11"
  - track: "Football Stadium - FPV Dutchman Mad House"
    url: "https://www.velocidrone.com/leaderboard/8/78/1.11"
  - track: "Football Stadium - FPV Dutchman Split-S Left"
    url: "https://www.velocidrone.com/leaderboard/8/79/1.11"
  - track: "Football Stadium - Jamboree"
    url: "https://www.velocidrone.com/leaderboard/8/4/1.11"
  - track: "Football Stadium - Kill Zone"
    url: "https://www.velocidrone.com/leaderboard/8/15/1.11"
  - track: "Football Stadium - MultiGP 2016 RF"
    url: "https://www.velocidrone.com/leaderboard/8/22/1.11"
  - track: "Football Stadium - MultiGP 2017 RF"
    url: "https://www.velocidrone.com/leaderboard/8/90/1.11"
  - track: "Football Stadium - MultiGP Bessel Run"
    url: "https://www.velocidrone.com/leaderboard/8/24/1.11"
  - track: "Football Stadium - MultiGP High Voltage"
    url: "https://www.velocidrone.com/leaderboard/8/37/1.11"
  - track: "Football Stadium - MultiGP Tsunami"
    url: "https://www.velocidrone.com/leaderboard/8/25/1.11"
  - track: "Football Stadium - MultiGP UTT 1"
    url: "https://www.velocidrone.com/leaderboard/8/23/1.11"
  - track: "Football Stadium - MultiGP UTT 5"
    url: "https://www.velocidrone.com/leaderboard/8/68/1.11"
  - track: "Football Stadium - MultiGP UTT 6"
    url: "https://www.velocidrone.com/leaderboard/8/148/1.11"
  - track: "Football Stadium - Pylons"
    url: "https://www.velocidrone.com/leaderboard/8/5/1.11"
  - track: "Football Stadium - Relay"
    url: "https://www.velocidrone.com/leaderboard/8/10/1.11"
  - track: "Football Stadium - SFPV MGP 1.0"
    url: "https://www.velocidrone.com/leaderboard/8/87/1.11"
  - track: "Football Stadium - SFPV VRL 5"
    url: "https://www.velocidrone.com/leaderboard/8/125/1.11"
  - track: "Football Stadium - SFPV VRL 7"
    url: "https://www.velocidrone.com/leaderboard/8/126/1.11"
  - track: "Football Stadium - Split-S"
    url: "https://www.velocidrone.com/leaderboard/8/19/1.11"
  - track: "Football Stadium - Split-S Reverse"
    url: "https://www.velocidrone.com/leaderboard/8/69/1.11"

#
# COUNTRYSIDE
#
  - track: "Countryside - 3D Championship 2016"
    url: "https://www.velocidrone.com/leaderboard/12/26/1.11"
  - track: "Countryside - Collision"
    url: "https://www.velocidrone.com/leaderboard/12/2/1.11"
  - track: "Countryside - Copse"
    url: "https://www.velocidrone.com/leaderboard/12/11/1.11"
  - track: "Countryside - EQ Field Run"
    url: "https://www.velocidrone.com/leaderboard/12/152/1.11"
  - track: "Countryside - FPV Dutchman Confusion"
    url: "https://www.velocidrone.com/leaderboard/12/76/1.11"
  - track: "Countryside - Gemfan"
    url: "https://www.velocidrone.com/leaderboard/12/1/1.11"
  - track: "Countryside - HDR Quickling"
    url: "https://www.velocidrone.com/leaderboard/12/83/1.11"
  - track: "Countryside - HDR- Fast Track 1.7"
    url: "https://www.velocidrone.com/leaderboard/12/77/1.11"
  - track: "Countryside - HDR-Trainer-LEVEL1"
    url: "https://www.velocidrone.com/leaderboard/12/142/1.11"
  - track: "Countryside - HDR-Trainer-LEVEL2"
    url: "https://www.velocidrone.com/leaderboard/12/143/1.11"
  - track: "Countryside - HDR-Trainer-LEVEL3"
    url: "https://www.velocidrone.com/leaderboard/12/144/1.11"
  - track: "Countryside - HDR-Trainer-LEVEL4"
    url: "https://www.velocidrone.com/leaderboard/12/145/1.11"
  - track: "Countryside - HDR-Trainer-LEVEL5"
    url: "https://www.velocidrone.com/leaderboard/12/146/1.11"
  - track: "Countryside - Lebach Final Event"
    url: "https://www.velocidrone.com/leaderboard/12/47/1.11"
  - track: "Countryside - London"
    url: "https://www.velocidrone.com/leaderboard/12/8/1.11"
  - track: "Countryside - MimaRaza GP"
    url: "https://www.velocidrone.com/leaderboard/12/66/1.11"
  - track: "Countryside - Pylons"
    url: "https://www.velocidrone.com/leaderboard/12/13/1.11"
  - track: "Countryside - Race MRCFK Austria"
    url: "https://www.velocidrone.com/leaderboard/12/64/1.11"
  - track: "Countryside - SFPV Propsman"
    url: "https://www.velocidrone.com/leaderboard/12/161/1.11"
  - track: "Countryside - SFPV VRL 2"
    url: "https://www.velocidrone.com/leaderboard/12/122/1.11"
  - track: "Countryside - Stade"
    url: "https://www.velocidrone.com/leaderboard/12/70/1.11"
  - track: "Countryside - Traditional"
    url: "https://www.velocidrone.com/leaderboard/12/14/1.11"
  - track: "Countryside - VV-Tradringar"
    url: "https://www.velocidrone.com/leaderboard/12/50/1.11"