# default user to search for
users:
  - name: "TALY"
    compare: true

# rank to compare against
rank: 50

# cachelifetime in seconds
cachelifetime: 600

scenes:
#
# RIVER2
#
  - track: "River2 - Bank Run"
    url: "https://www.velocidrone.com/leaderboard/23/117/1.11"
  - track: "River2 - Castle Shake Down"
    url: "https://www.velocidrone.com/leaderboard/23/118/1.11"
  - track: "River2 - HDR-CastleBlack-FIRE"
    url: "https://www.velocidrone.com/leaderboard/23/140/1.11"
  - track: "River2 - HDR-WhiteCastle-SP"
    url: "https://www.velocidrone.com/leaderboard/23/164/1.11"
  - track: "River2 - Pylons"
    url: "https://www.velocidrone.com/leaderboard/23/112/1.11"
  - track: "River2 - RiverSlalom"
    url: "https://www.velocidrone.com/leaderboard/23/119/1.11"
  - track: "River2 - SFPV Castle Run V2"
    url: "https://www.velocidrone.com/leaderboard/23/155/1.11"
  - track: "River2 - SFPV Dive"
    url: "https://www.velocidrone.com/leaderboard/23/156/1.11"
  - track: "River2 - SFPV Game of Drones"
    url: "https://www.velocidrone.com/leaderboard/23/132/1.11"
  - track: "River2 - SFPV H20Fire"
    url: "https://www.velocidrone.com/leaderboard/23/158/1.11"
  - track: "River2 - SFPV Lake House"
    url: "https://www.velocidrone.com/leaderboard/23/159/1.11"
  - track: "River2 - SFPV Matterhorn"
    url: "https://www.velocidrone.com/leaderboard/23/160/1.11"
  - track: "River2 - SFPV Torch Run V2"
    url: "https://www.velocidrone.com/leaderboard/23/162/1.11"

#
# SPORTSHALL
#
  - track: "SportsHall - Mini Rush"
    url: "https://www.velocidrone.com/leaderboard/21/72/1.11"
  - track: "SportsHall - MultiGP Round 2 FNL"
    url: "https://www.velocidrone.com/leaderboard/21/115/1.11"
  - track: "SportsHall - Pylons"
    url: "https://www.velocidrone.com/leaderboard/21/57/1.11"
  - track: "SportsHall - School Track"
    url: "https://www.velocidrone.com/leaderboard/21/58/1.11"

#
# SUBWAY
#
  - track: "Subway - Upstairs Downstairs"
    url: "https://www.velocidrone.com/leaderboard/15/36/1.11"
  - track: "Subway - All Stations"
    url: "https://www.velocidrone.com/leaderboard/15/39/1.11"
  - track: "Subway - Pylons"
    url: "https://www.velocidrone.com/leaderboard/15/33/1.11"
  - track: "Subway - RailRun"
    url: "https://www.velocidrone.com/leaderboard/15/167/1.11"
  - track: "Subway - Station Circuit"
    url: "https://www.velocidrone.com/leaderboard/15/35/1.11"
  - track: "Subway - Train Weave"
    url: "https://www.velocidrone.com/leaderboard/15/38/1.11"

#
# HANGAR
#
  - track: "Hangar - Pylons"
    url: "https://www.velocidrone.com/leaderboard/3/20/1.11"
  - track: "Hangar - BoxCars"
    url: "https://www.velocidrone.com/leaderboard/3/7/1.11"
  - track: "Hangar - Porco Stadium"
    url: "https://www.velocidrone.com/leaderboard/3/49/1.11"

#
# INDUSTRIAL WASTELAND
#
  - track: "Industrial Wasteland - Industrial Flag Race"
    url: "https://www.velocidrone.com/leaderboard/7/61/1.11"
  - track: "Industrial Wasteland - Porco Apocalypse"
    url: "https://www.velocidrone.com/leaderboard/7/63/1.11"
  - track: "Industrial Wasteland - Pylons"
    url: "https://www.velocidrone.com/leaderboard/7/21/1.11"
  - track: "Industrial Wasteland - SFPV Industry Loop"
    url: "https://www.velocidrone.com/leaderboard/7/85/1.11"
  - track: "Industrial Wasteland - SFPV Industry Power"
    url: "https://www.velocidrone.com/leaderboard/7/86/1.11"
  - track: "Industrial Wasteland - SFPV VRL 1"
    url: "https://www.velocidrone.com/leaderboard/7/121/1.11"
  - track: "Industrial Wasteland - Tower Drop"
    url: "https://www.velocidrone.com/leaderboard/7/31/1.11"

#
# FOOTBALL STADIUM
#
  - track: "Football Stadium - Bexbach"
    url: "https://www.velocidrone.com/leaderboard/8/46/1.11"
  - track: "Football Stadium - Block Madness"
    url: "https://www.velocidrone.com/leaderboard/8/18/1.11"
  - track: "Football Stadium - Complex"
    url: "https://www.velocidrone.com/leaderboard/8/3/1.11"
  - track: "Football Stadium - CrossOver"
    url: "https://www.velocidrone.com/leaderboard/8/9/1.11"
  - track: "Football Stadium - FPV Dutchman Insanity"
    url: "https://www.velocidrone.com/leaderboard/8/80/1.11"
  - track: "Football Stadium - FPV Dutchman Mad House"
    url: "https://www.velocidrone.com/leaderboard/8/78/1.11"
  - track: "Football Stadium - FPV Dutchman Split-S Left"
    url: "https://www.velocidrone.com/leaderboard/8/79/1.11"
  - track: "Football Stadium - Jamboree"
    url: "https://www.velocidrone.com/leaderboard/8/4/1.11"
  - track: "Football Stadium - Kill Zone"
    url: "https://www.velocidrone.com/leaderboard/8/15/1.11"
  - track: "Football Stadium - MultiGP 2016 RF"
    url: "https://www.velocidrone.com/leaderboard/8/22/1.11"
  - track: "Football Stadium - MultiGP 2017 RF"
    url: "https://www.velocidrone.com/leaderboard/8/90/1.11"
  - track: "Football Stadium - MultiGP Bessel Run"
    url: "https://www.velocidrone.com/leaderboard/8/24/1.11"
  - track: "Football Stadium - MultiGP High Voltage"
    url: "https://www.velocidrone.com/leaderboard/8/37/1.11"
  - track: "Football Stadium - MultiGP Tsunami"
    url: "https://www.velocidrone.com/leaderboard/8/25/1.11"
  - track: "Football Stadium - MultiGP UTT 1"
    url: "https://www.velocidrone.com/leaderboard/8/23/1.11"
  - track: "Football Stadium - MultiGP UTT 5"
    url: "https://www.velocidrone.com/leaderboard/8/68/1.11"
  - track: "Football Stadium - MultiGP UTT 6"
    url: "https://www.velocidrone.com/leaderboard/8/148/1.11"
  - track: "Football Stadium - Pylons"
    url: "https://www.velocidrone.com/leaderboard/8/5/1.11"
  - track: "Football Stadium - Relay"
    url: "https://www.velocidrone.com/leaderboard/8/10/1.11"
  - track: "Football Stadium - SFPV MGP 1.0"
    url: "https://www.velocidrone.com/leaderboard/8/87/1.11"
  - track: "Football Stadium - SFPV VRL 5"
    url: "https://www.velocidrone.com/leaderboard/8/125/1.11"
  - track: "Football Stadium - SFPV VRL 7"
    url: "https://www.velocidrone.com/leaderboard/8/126/1.11"
  - track: "Football Stadium - Split-S"
    url: "https://www.velocidrone.com/leaderboard/8/19/1.11"
  - track: "Football Stadium - Split-S Reverse"
    url: "https://www.velocidrone.com/leaderboard/8/69/1.11"
  - track: "Football Stadium - SFPV VRL14"
    url: "https://www.velocidrone.com/leaderboard/8/169/1.11"
  - track: "Football Stadium - HDR OG Raceway Joes Ss"
    url: "https://www.velocidrone.com/leaderboard/8/170/1.11"
  - track: "Football Stadium - SFPV VRL 16"
    url: "https://www.velocidrone.com/leaderboard/8/173/1.11"
  - track: "Football Stadium - MultiGP 2018 RQ"
    url: "https://www.velocidrone.com/leaderboard/8/182/1.11"

#
# COUNTRYSIDE
#
  - track: "Countryside - 3D Championship 2016"
    url: "https://www.velocidrone.com/leaderboard/12/26/1.11"
  - track: "Countryside - Collision"
    url: "https://www.velocidrone.com/leaderboard/12/2/1.11"
  - track: "Countryside - Copse"
    url: "https://www.velocidrone.com/leaderboard/12/11/1.11"
  - track: "Countryside - EQ Field Run"
    url: "https://www.velocidrone.com/leaderboard/12/152/1.11"
  - track: "Countryside - FPV Dutchman Confusion"
    url: "https://www.velocidrone.com/leaderboard/12/76/1.11"
  - track: "Countryside - Gemfan"
    url: "https://www.velocidrone.com/leaderboard/12/1/1.11"
  - track: "Countryside - HDR Quickling"
    url: "https://www.velocidrone.com/leaderboard/12/83/1.11"
  - track: "Countryside - HDR- Fast Track 1.7"
    url: "https://www.velocidrone.com/leaderboard/12/77/1.11"
  - track: "Countryside - HDR-Trainer-LEVEL1"
    url: "https://www.velocidrone.com/leaderboard/12/142/1.11"
  - track: "Countryside - HDR-Trainer-LEVEL2"
    url: "https://www.velocidrone.com/leaderboard/12/143/1.11"
  - track: "Countryside - HDR-Trainer-LEVEL3"
    url: "https://www.velocidrone.com/leaderboard/12/144/1.11"
  - track: "Countryside - HDR-Trainer-LEVEL4"
    url: "https://www.velocidrone.com/leaderboard/12/145/1.11"
  - track: "Countryside - HDR-Trainer-LEVEL5"
    url: "https://www.velocidrone.com/leaderboard/12/146/1.11"
  - track: "Countryside - Lebach Final Event"
    url: "https://www.velocidrone.com/leaderboard/12/47/1.11"
  - track: "Countryside - London"
    url: "https://www.velocidrone.com/leaderboard/12/8/1.11"
  - track: "Countryside - MimaRaza GP"
    url: "https://www.velocidrone.com/leaderboard/12/66/1.11"
  - track: "Countryside - Pylons"
    url: "https://www.velocidrone.com/leaderboard/12/13/1.11"
  - track: "Countryside - Race MRCFK Austria"
    url: "https://www.velocidrone.com/leaderboard/12/64/1.11"
  - track: "Countryside - SFPV Propsman"
    url: "https://www.velocidrone.com/leaderboard/12/161/1.11"
  - track: "Countryside - SFPV VRL 2"
    url: "https://www.velocidrone.com/leaderboard/12/122/1.11"
  - track: "Countryside - Stade"
    url: "https://www.velocidrone.com/leaderboard/12/70/1.11"
  - track: "Countryside - Traditional"
    url: "https://www.velocidrone.com/leaderboard/12/14/1.11"
  - track: "Countryside - VV-Tradringar"
    url: "https://www.velocidrone.com/leaderboard/12/50/1.11"
  - track: "Countryside - VRL9 Relay Track"
    url: "https://www.velocidrone.com/leaderboard/12/165/1.11"

#
# Night Factory
#
  - track: "Night Factory - Barracks"
    url: "https://www.velocidrone.com/leaderboard/13/75/1.11"
  - track: "Night Factory - Factory Run"
    url: "https://www.velocidrone.com/leaderboard/13/28/1.11"
  - track: "Night Factory - Mind The Gap"
    url: "https://www.velocidrone.com/leaderboard/13/32/1.11"
  - track: "Night Factory - Neon Circuit"
    url: "https://www.velocidrone.com/leaderboard/13/29/1.11"
  - track: "Night Factory - Pinch Points"
    url: "https://www.velocidrone.com/leaderboard/13/30/1.11"
  - track: "Night Factory - Pylons"
    url: "https://www.velocidrone.com/leaderboard/13/27/1.11"
  - track: "Night Factory - SFPV VRL 9"
    url: "https://www.velocidrone.com/leaderboard/13/163/1.11"

#
# Karting Track
#
  - track: "Karting Track - Pylons"
    url: "https://www.velocidrone.com/leaderboard/14/41/1.11"
  - track: "Karting Track - RaceDrones Classic"
    url: "https://www.velocidrone.com/leaderboard/14/34/1.11"
  - track: "Karting Track - Track Lap"
    url: "https://www.velocidrone.com/leaderboard/14/40/1.11"
  - track: "Karting Track - SFPV VRL15"
    url: "https://www.velocidrone.com/leaderboard/14/172/1.11"
  - track: "Karting Track - American Canyon Advanced"
    url: "https://www.velocidrone.com/leaderboard/14/178/1.11"
  - track: "Karting Track - American Canyon Beginner"
    url: "https://www.velocidrone.com/leaderboard/14/176/1.11"
  - track: "Karting Track - American Canyon Intermediate"
    url: "https://www.velocidrone.com/leaderboard/14/177/1.11"
  - track: "Karting Track - American Canyon Insane"
    url: "https://www.velocidrone.com/leaderboard/14/179/1.11"

#
# Blank Canvas Day
#
  - track: "Blank Canvas Day - HDR-Apples-Orchards1.9.3"
    url: "https://www.velocidrone.com/leaderboard/16/98/1.11"
  - track: "Blank Canvas Day - HDR-Infinity1.9.8"
    url: "https://www.velocidrone.com/leaderboard/16/108/1.11"
  - track: "Blank Canvas Day - HDR-SnapBack1.9.5"
    url: "https://www.velocidrone.com/leaderboard/16/99/1.11"
  - track: "Blank Canvas Day - HDR-Storage-A-GoGo1.9.6"
    url: "https://www.velocidrone.com/leaderboard/16/107/1.11"
  - track: "Blank Canvas Day - HDR-Woodie1.9.6"
    url: "https://www.velocidrone.com/leaderboard/16/100/1.11"
  - track: "Blank Canvas Day - IDN-2017-Mod"
    url: "https://www.velocidrone.com/leaderboard/16/120/1.11"
  - track: "Blank Canvas Day - Ireland - IDN 2016"
    url: "https://www.velocidrone.com/leaderboard/16/60/1.11"
  - track: "Blank Canvas Day - MiniRock"
    url: "https://www.velocidrone.com/leaderboard/16/116/1.11"
  - track: "Blank Canvas Day - Nite Racing Sessions 2"
    url: "https://www.velocidrone.com/leaderboard/16/82/1.11"
  - track: "Blank Canvas Day - Official Track Seoul"
    url: "https://www.velocidrone.com/leaderboard/16/109/1.11"
  - track: "Blank Canvas Day - Pylons"
    url: "https://www.velocidrone.com/leaderboard/16/42/1.11"
  - track: "Blank Canvas Day - Quadcopters Track"
    url: "https://www.velocidrone.com/leaderboard/16/96/1.11"
  - track: "Blank Canvas Day - SFPV VRL 3"
    url: "https://www.velocidrone.com/leaderboard/16/123/1.11"
  - track: "Blank Canvas Day - Swiss Drone Nationals 2016"
    url: "https://www.velocidrone.com/leaderboard/16/65/1.11"
  - track: "Blank Canvas Day - TOG RHINO"
    url: "https://www.velocidrone.com/leaderboard/16/149/1.11"
  - track: "Blank Canvas Day - Weston Park 2017"
    url: "https://www.velocidrone.com/leaderboard/16/110/1.11"
  - track: "Blank Canvas Day - SFPV VRL13"
    url: "https://www.velocidrone.com/leaderboard/16/168/1.11"
  - track: "Blank Canvas Day - West Coast DRL"
    url: "https://www.velocidrone.com/leaderboard/16/171/1.11"
  - track: "Blank Canvas Day - VRL17"
    url: "https://www.velocidrone.com/leaderboard/16/174/1.11"
  - track: "Blank Canvas Day - SFPV VRL 19"
    url: "https://www.velocidrone.com/leaderboard/16/180/1.11"
  - track: "Blank Canvas Day - SFPV VRL 20"
    url: "https://www.velocidrone.com/leaderboard/16/181/1.11"
  - track: "Blank Canvas Day - Uvify Tournament Track"
    url: "https://www.velocidrone.com/leaderboard/16/175/1.11"

#
# Blank Canvas Night
#
  - track: "Blank Canvas Night - FPV Dutchman Neon Flash"
    url: "https://www.velocidrone.com/leaderboard/17/74/1.11"
  - track: "Blank Canvas Night - Neon Cage"
    url: "https://www.velocidrone.com/leaderboard/17/51/1.11"
  - track: "Blank Canvas Night - Night Train"
    url: "https://www.velocidrone.com/leaderboard/17/62/1.11"
  - track: "Blank Canvas Night - Proximity"
    url: "https://www.velocidrone.com/leaderboard/17/81/1.11"
  - track: "Blank Canvas Night - Pylons"
    url: "https://www.velocidrone.com/leaderboard/17/43/1.11"

#
# Birmingham NEC
#
  - track: "Birmingham NEC - Barnstorm"
    url: "https://www.velocidrone.com/leaderboard/18/73/1.11"
  - track: "Birmingham NEC - iSeries 1"
    url: "https://www.velocidrone.com/leaderboard/18/55/1.11"
  - track: "Birmingham NEC - iSeries 2"
    url: "https://www.velocidrone.com/leaderboard/18/44/1.11"
  - track: "Birmingham NEC - Pylons"
    url: "https://www.velocidrone.com/leaderboard/18/67/1.11"

#
# Warehouse
#
  - track: "Warehouse - Canon"
    url: "https://www.velocidrone.com/leaderboard/19/59/1.11"
  - track: "Warehouse - FPVgan - Jam Factory"
    url: "https://www.velocidrone.com/leaderboard/19/153/1.11"
  - track: "Warehouse - Pylons"
    url: "https://www.velocidrone.com/leaderboard/19/52/1.11"
  - track: "Warehouse - Warehouse Slalom"
    url: "https://www.velocidrone.com/leaderboard/19/56/1.11"

#
# Underground Carpark
#
  - track: "Underground Carpark - Rush Hour"
    url: "https://www.velocidrone.com/leaderboard/20/71/1.11"
  - track: "Underground Carpark - Pylons"
    url: "https://www.velocidrone.com/leaderboard/20/53/1.11"
  - track: "Underground Carpark - Twin Floors"
    url: "https://www.velocidrone.com/leaderboard/20/54/1.11"

#
# Coastel
#
  - track: "Coastel - HDR-Cargo1.8.6"
    url: "https://www.velocidrone.com/leaderboard/22/91/1.11"
  - track: "Coastel - HDR-FloatersEXTREME1.9.2"
    url: "https://www.velocidrone.com/leaderboard/22/97/1.11"
  - track: "Coastel - HDR-GateTime1.8.6"
    url: "https://www.velocidrone.com/leaderboard/22/93/1.11"
  - track: "Coastel - HDR-ShipIT1.8.6"
    url: "https://www.velocidrone.com/leaderboard/22/94/1.11"
  - track: "Coastel - HDR-SkippinStones1.8.6"
    url: "https://www.velocidrone.com/leaderboard/22/95/1.11"
  - track: "Coastel - Pylons"
    url: "https://www.velocidrone.com/leaderboard/22/88/1.11"
  - track: "Coastel - SFPV Containment"
    url: "https://www.velocidrone.com/leaderboard/22/101/1.11"
  - track: "Coastel - SFPV Ghost Ship"
    url: "https://www.velocidrone.com/leaderboard/22/102/1.11"
  - track: "Coastel - SFPV Holy Ship"
    url: "https://www.velocidrone.com/leaderboard/22/103/1.11"
  - track: "Coastel - SFPV Mill Ave"
    url: "https://www.velocidrone.com/leaderboard/22/104/1.11"
  - track: "Coastel - SFPV Smoke Stacks"
    url: "https://www.velocidrone.com/leaderboard/22/105/1.11"
  - track: "Coastel - SFPV Team Black Sheep Championship"
    url: "https://www.velocidrone.com/leaderboard/22/137/1.11"
  - track: "Coastel - SFPV Tower of Terror"
    url: "https://www.velocidrone.com/leaderboard/22/106/1.11"
  - track: "Coastel - SFPV Tower of Terror 2"
    url: "https://www.velocidrone.com/leaderboard/22/139/1.11"
  - track: "Coastel - SFPV VRL 4"
    url: "https://www.velocidrone.com/leaderboard/22/124/1.11"

#
# City
#
  - track: "City - Pylons"
    url: "https://www.velocidrone.com/leaderboard/24/111/1.11"
  - track: "City - SFPV Around the Block"
    url: "https://www.velocidrone.com/leaderboard/24/154/1.11"
  - track: "City - SFPV CITY 2"
    url: "https://www.velocidrone.com/leaderboard/24/129/1.11"
  - track: "City - SFPV Downtown"
    url: "https://www.velocidrone.com/leaderboard/24/157/1.11"

#
# Red Bull Ring
#
  - track: "Red Bull Ring - HDR-RedBull-Mod1"
    url: "https://www.velocidrone.com/leaderboard/25/151/1.11"
  - track: "Red Bull Ring - Pylons"
    url: "https://www.velocidrone.com/leaderboard/25/113/1.11"
  - track: "Red Bull Ring - Redbull DR.ONE"
    url: "https://www.velocidrone.com/leaderboard/25/114/1.11"
  - track: "Red Bull Ring - SFPV DRONE"
    url: "https://www.velocidrone.com/leaderboard/25/131/1.11"
